name: Build OS•DEMYAN GSI

on:
  workflow_dispatch:

jobs:
  build-gsi:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y e2fsprogs android-sdk-libsparse-utils python3 p7zip-full

    - name: Download and Low-Memory Extract Android 17
      run: |
        # Скачиваем официальный образ Android 17
        wget -q https://google.com -O donor.zip
        
        # Распаковываем через 7z напрямую на диск с минимальным потреблением ОЗУ
        mkdir -p donor_files
        7z x donor.zip -odonor_files/ -y
        rm donor.zip
        
        # Конвертируем образ
        simg2img donor_files/system.img system.raw.img
        rm -rf donor_files

    - name: Extract System Image Files
      run: |
        git clone https://github.com
        python3 imgextractor/imgextractor.py system.raw.img output_folder
        rm system.raw.img

    - name: Inject OS•DEMYAN DNA
      run: |
        # Прописываем имя системы в настройки
        sed -i 's/ro.build.display.id=.*/ro.build.display.id=OS•DEMYAN v1.0/g' output_folder/system/build.prop
        
        # Активируем эффект матового стекла Liquid Glass (Blur)
        echo "ro.surface_flinger.supports_background_blur=1" >> output_folder/system/build.prop
        echo "ro.sf.blurs_are_expensive=0" >> output_folder/system/build.prop
        
        # Интеграция лаунчера, если он будет загружен
        if [ -f "DemyanLauncher.apk" ]; then
          mkdir -p output_folder/system/priv-app/DemyanLauncher
          cp DemyanLauncher.apk output_folder/system/priv-app/DemyanLauncher/
        fi
        
        # Интеграция анимации загрузки, если она будет загружена
        if [ -f "bootanimation.zip" ]; then
          cp bootanimation.zip output_folder/system/media/
        fi

    - name: Pack OS•DEMYAN GSI
      run: |
        # Упаковываем файлы обратно в систему ext4
        mke2fs -t ext4 -b 4096 -I 256 -O ^has_journal -M /system -d output_folder system_modified.raw.img
        # Финальное сжатие в формат GSI
        img2simg system_modified.raw.img system_os_demyan.img

    - name: Upload Finished GSI Image
      uses: actions/upload-artifact@v4
      with:
        name: OS-DEMYAN-Android17-GSI
        path: system_os_demyan.img
        compression-level: 6
